{
 "title": "FSG PTE",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostsRegEx",
    "label": "Hosts",
    "query": "SHOW TAG VALUES FROM \"cpu\" WITH KEY = \"host\" WHERE host =~ /pte11fsg/"
   },
   {
    "name": "appSubname",
    "label": "JVM App",
    "query": "SHOW TAG VALUES FROM \"heap\" WITH KEY = \"appSubname\" WHERE host =~ /pte11fsg/"
   },
   { "name": "connPoolRegex", "label": "Conn pool", "query": "${VAR_CONNPOOLREGEX}" },
   { "name": "jmeterappname", "query": "${VAR_JMETERAPPNAME}" },
   { "name": "aggregation", "label": "Aggregation Interval", "query": "1,10,30,60,600,1800,3600" },
   { "name": "TestType", "label": "TestType", "query": "Baseline, Capacity, Endurance" }
  ]
 },
 "panels": [
  { "title": "Jmeter Results", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Vusers vs Throughput Graph",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Vusers",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"maxActiveThreads\") FROM \"requestsMetrics\" WHERE $timeFilter AND projectName='$jmeterappname' GROUP BY time(10s) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Throughput",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  count(\"respTime\")/$aggregation FROM \"requestsMetrics\" WHERE $timeFilter AND projectName='$jmeterappname' GROUP BY time(10s) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Running Vusers",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"maxActiveThreads\") FROM \"requestsMetrics\" WHERE $timeFilter AND projectName='$jmeterappname' GROUP BY \"maxActiveThreads\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Throughput",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  count(\"respTime\")/$aggregation FROM \"requestsMetrics\" WHERE $timeFilter GROUP BY time([[aggregation]]s) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  count(\"respTime\") FROM \"requestsMetrics\" WHERE $timeFilter AND projectName='$jmeterappname'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "#Passed Requests",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 8 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT 1 - sum(\"errCount\")/count(\"respTime\") FROM \"requestsMetrics\" WHERE $timeFilter AND projectName='$jmeterappname'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "#Failed Requests",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 8 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"errCount\")/count(\"respTime\") FROM \"requestsMetrics\" WHERE $timeFilter AND projectName='$jmeterappname'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Aggregate Report Table",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(respTime) as Samples, percentile(respTime, 90) as \"90%\",percentile(respTime, 95) as \"95%\",percentile(respTime, 99) as \"99%\", mean(respTime) as Avg, min(respTime) as Min, median(respTime) as Median, max(respTime) as Max, (sum(errCount)/count(respTime)) as \"Error Rate\" FROM \"requestsMetrics\"  WHERE $timeFilter AND projectName='$jmeterappname' AND testType = 'Baseline' GROUP BY requestName order by asc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Error Rate Graph",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  count(\"errCount\")/$aggregation FROM \"requestsMetrics\" WHERE $timeFilter AND projectName='$jmeterappname' GROUP BY time(10s) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage Summary",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT 100-mean(\"usage_idle\") as \"cpu.mean\", 100-percentile(\"usage_idle\",5) as \"cpu.perc95\", 100-min(\"usage_idle\") as \"cpu.max\" FROM \"cpu\" WHERE \"host\" =~ /$hostsRegEx/ AND $timeFilter  GROUP BY \"host\", appSubname fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Load Averages (1 min)",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"load1\"), mean(\"load1\"), percentile(\"load1\",95) as perc95 FROM \"system\" WHERE \"host\" =~ /$hostsRegEx/ AND $timeFilter GROUP BY  \"host\", appSubname fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization %",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "cpu",
       "query": "SELECT 100-max(\"usage_idle\") FROM \"cpu\" WHERE \"host\" =~ /$hostsRegEx/ AND $timeFilter GROUP BY time($interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "usage_idle" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "bnpte10pngge001" }
       ]
      }
     ]
    },
    {
     "title": "CPU User %",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host.cpu_user_util",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "cpu",
       "query": "SELECT max(\"usage_user\") FROM \"cpu\" WHERE \"host\" =~ /$hostsRegEx/ AND $timeFilter GROUP BY time($interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "usage_user" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "select tag value" }
       ]
      }
     ]
    },
    {
     "title": "CPU IOWait %",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host.cpu_iowait_util",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"usage_iowait\") FROM \"cpu\" WHERE \"host\" =~ /$hostsRegEx/ AND $timeFilter GROUP BY time($interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "target": "SELECT max(\"usage_user\") FROM \"cpu\" WHERE \"host\" =~ /$hostsRegEx/ AND $timeFilter GROUP BY time($interval), \"host\" fill(null)"
      }
     ]
    },
    {
     "title": "CPU System %",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"usage_system\") FROM \"cpu\" WHERE \"host\" =~ /$hostsRegEx/ AND $timeFilter GROUP BY time($interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "CPU Nice %",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"usage_nice\") FROM \"cpu\" WHERE \"host\" =~ /$hostsRegEx/ AND $timeFilter GROUP BY time($interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "CPU Irq %",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"usage_irq\") + max(\"usage_softirq\") FROM \"cpu\" WHERE \"host\" =~ /$hostsRegEx/ AND $timeFilter GROUP BY time($interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "CPU Idle %",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"usage_idle\") FROM \"cpu\" WHERE \"host\" =~ /$hostsRegEx/ AND $timeFilter GROUP BY time($interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Summary",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"OC\") - max(\"OU\") as \"old.free.min\", max(\"OC\") as \"old.cap.max\", max(\"OU\") as \"old.used.max\", mean(\"OU\") as \"old.used.mean\", max(\"MU\") as \"meta.used.max\", mean(\"MU\") as \"meta.used.mean\", max(\"EU\") as \"eden.used.max\", mean(\"EU\") as \"eden.used.mean\" FROM \"heap\" WHERE \"host\" =~ /$hostsRegEx/ AND appSubname =~ /$appSubname/ AND $timeFilter GROUP BY host, appSubname fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "GC Summary",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"YGC\")-min(\"YGC\") as \"young.gcs\", max(\"YGCT\")-min(\"YGCT\") as \"young.total.secs\", ((max(\"YGCT\")-min(\"YGCT\")) * 1000) / (max(\"YGC\")-min(\"YGC\"))  as \"young.mean.ms\", max(\"FGC\")-min(\"FGC\") as \"full.gcs\", max(\"FGCT\")-min(\"FGCT\") as \"full.total.secs\", ((max(\"FGCT\")-min(\"FGCT\")) * 1000) / (max(\"FGC\")-min(\"FGC\"))  as \"full.mean.ms\" FROM \"heap\" WHERE \"host\" =~ /$hostsRegEx/ AND appSubname =~ /$appSubname/ AND $timeFilter GROUP BY host, appSubname fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Old Generation",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "kbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host.$tag_appSubname.capacity",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "app_exec",
       "query": "SELECT max(\"OC\") FROM \"heap\" WHERE \"host\" =~ /$hostsRegEx/ AND appSubname =~ /$appSubname/ AND $timeFilter GROUP BY time($interval), host, appSubname fill(null)",
       "select": [
        [
         { "params": [ "OC" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        {
         "key": "host",
         "operator": "=",
         "value": "WHERE \"host\" =~ /$hostsRegEx/"
        }
       ]
      },
      {
       "alias": "$tag_host.$tag_appSubname.used",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"OU\") FROM \"heap\" WHERE \"host\" =~ /$hostsRegEx/ AND appSubname =~ /$appSubname/ AND $timeFilter GROUP BY time($interval), host, appSubname fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Eden Generation",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "kbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host.$tag_appSubname.capacity",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "app_exec",
       "query": "SELECT max(\"EC\") FROM \"heap\" WHERE \"host\" =~ /$hostsRegEx/ AND appSubname =~ /$appSubname/ AND $timeFilter GROUP BY time($interval), host, appSubname fill(null)",
       "select": [
        [
         { "params": [ "OC" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        {
         "key": "host",
         "operator": "=",
         "value": "WHERE \"host\" =~ /$hostsRegEx/"
        }
       ]
      },
      {
       "alias": "$tag_host.$tag_appSubname.used",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"EU\") FROM \"heap\" WHERE \"host\" =~ /$hostsRegEx/ AND appSubname =~ /$appSubname/ AND $timeFilter GROUP BY time($interval), host, appSubname fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Full GC Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "ms", "label": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_host.$tag_appSubname",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(max(\"FGCT\"),10s)*1000 FROM \"heap\" WHERE \"host\" =~ /$hostsRegEx/ AND appSubname =~ /$appSubname/ AND $timeFilter GROUP BY time($interval), host, appSubname fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Young GC Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "ms", "label": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_host.$tag_appSubname",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(max(\"YGCT\"),10s)*1000 FROM \"heap\" WHERE \"host\" =~ /$hostsRegEx/ AND appSubname =~ /$appSubname/ AND $timeFilter GROUP BY time($interval), host, appSubname fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "GC Count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host.$tag_appSubname.young",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "app_exec",
       "query": "SELECT non_negative_derivative(max(\"YGC\"),10s) FROM \"heap\" WHERE \"host\" =~ /$hostsRegEx/ AND appSubname =~ /$appSubname/ AND $timeFilter GROUP BY time($interval), host, appSubname fill(null)",
       "select": [
        [
         { "params": [ "OC" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        {
         "key": "host",
         "operator": "=",
         "value": "WHERE \"host\" =~ /$hostsRegEx/"
        }
       ]
      },
      {
       "alias": "$tag_host.$tag_appSubname.full",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(max(\"FGC\"),10s) FROM \"heap\" WHERE \"host\" =~ /$hostsRegEx/ AND appSubname =~ /$appSubname/ AND $timeFilter GROUP BY time($interval), host, appSubname fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Survivor Space",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "kbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host.$tag_appSubname.used",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"S0U\") FROM \"heap\" WHERE \"host\" =~ /$hostsRegEx/ AND appSubname =~ /$appSubname/ AND $timeFilter GROUP BY time($interval), host, appSubname fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host.$tag_appSubname.capacity",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"S0C\") FROM \"heap\" WHERE \"host\" =~ /$hostsRegEx/ AND appSubname =~ /$appSubname/ AND $timeFilter GROUP BY time($interval), host, appSubname fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host.$tag_appSubname.capacity",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"S1C\") FROM \"heap\" WHERE \"host\" =~ /$hostsRegEx/ AND appSubname =~ /$appSubname/ AND $timeFilter GROUP BY time($interval), host, appSubname fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host.$tag_appSubname.used",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"S1U\") FROM \"heap\" WHERE \"host\" =~ /$hostsRegEx/ AND appSubname =~ /$appSubname/ AND $timeFilter GROUP BY time($interval), host, appSubname fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Metaspace Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "kbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host.$tag_appSubname.used",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"MU\") FROM \"heap\" WHERE \"host\" =~ /$hostsRegEx/ AND appSubname =~ /$appSubname/ AND $timeFilter GROUP BY time($interval), host, appSubname fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host.$tag_appSubname.capacity",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"MC\") FROM \"heap\" WHERE \"host\" =~ /$hostsRegEx/ AND appSubname =~ /$appSubname/ AND $timeFilter GROUP BY time($interval), host, appSubname fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "CCS Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "kbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host.$tag_appSubname.used",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"CCSU\") FROM \"heap\" WHERE \"host\" =~ /$hostsRegEx/ AND appSubname =~ /$appSubname/ AND $timeFilter GROUP BY time($interval), host, appSubname fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host.$tag_appSubname.capacity",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"CCSC\") FROM \"heap\" WHERE \"host\" =~ /$hostsRegEx/ AND appSubname =~ /$appSubname/ AND $timeFilter GROUP BY time($interval), host, appSubname fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Tenured Bytes Per Second",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "kbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(max(\"OU\"), 10s) FROM \"heap\" WHERE \"host\" =~ /^$hostsRegEx$/ AND $timeFilter GROUP BY time($interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Eden Bytes Per Second",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "kbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host.BytesPerSecond",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(max(\"EU\"), 10s) FROM \"heap\" WHERE \"host\" =~ /$hostsRegEx$/ AND $timeFilter GROUP BY time($interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Open File Descriptors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short", "label": "Open FIles" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"value\") FROM \"OpenFileDescriptorCount\" WHERE \"host\" =~ /^$hostsRegEx/ AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "NIO Buffers Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host.direct.TotalCapacity",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"value\") FROM \"jvm.nio.bufferpool.direct.TotalCapacity\" WHERE \"host\" =~ /^$hostsRegEx/ AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host.mapped.TotalCapacity",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"value\") FROM \"jvm.nio.bufferpool.mapped.TotalCapacity\" WHERE \"host\" =~ /^$hostsRegEx/ AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "NIO Buffer Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host.direct.Count",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"value\") FROM \"jvm.nio.bufferpool.direct.Count\" WHERE \"host\" =~ /^$hostsRegEx/ AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host.mapped.Count",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"value\") FROM \"jvm.nio.bufferpool.mapped.Count\" WHERE \"host\" =~ /^$hostsRegEx/ AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Web Server Threads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host.threads",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jvm.webserver.threads",
       "query": "SELECT max(\"value\") FROM \"jvm.webserver.0.threads\" WHERE \"host\" =~ /$hostsRegEx/ AND $timeFilter GROUP BY time($interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host.idleThreads",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jvm.webserver.threads",
       "query": "SELECT min(\"value\") FROM \"jvm.webserver.0.idleThreads\" WHERE \"host\" =~ /$hostsRegEx/ AND $timeFilter GROUP BY time($interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Load Averages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "1 Min",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 118 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"load1\") FROM \"system\" WHERE \"host\" =~ /$hostsRegEx/ AND $timeFilter GROUP BY time($interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "5 Mins",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 118 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"load5\") FROM \"system\" WHERE \"host\" =~ /$hostsRegEx/ AND $timeFilter GROUP BY time($interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "15 Mins",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 118 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"load15\") FROM \"system\" WHERE \"host\" =~ /$hostsRegEx/ AND $timeFilter GROUP BY time($interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk IO Read",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 119 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "query": "SELECT derivative(mean(\"read_bytes\"), 1s) FROM \"diskio\" WHERE \"host\" =~ /$hostsRegEx/ AND $timeFilter GROUP BY time($interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "read_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "bnpte11cbswj005" }
       ]
      }
     ]
    },
    {
     "title": "Disk IO Write",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 119 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "query": "SELECT derivative(mean(\"write_bytes\"), 1s) FROM \"diskio\" WHERE \"host\" =~ /$hostsRegEx/ AND $timeFilter GROUP BY time($interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "read_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "bnpte11cbswj005" }
       ]
      }
     ]
    },
    {
     "title": "Disk IO Read Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 126 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "query": "SELECT derivative(mean(\"read_time\"), 1s) FROM \"diskio\" WHERE \"host\" =~ /$hostsRegEx/ AND $timeFilter GROUP BY time($interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "read_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "bnpte11cbswj005" }
       ]
      }
     ]
    },
    {
     "title": "Disk IO Write Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 126 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "query": "SELECT derivative(mean(\"write_time\"), 1s) FROM \"diskio\" WHERE \"host\" =~ /$hostsRegEx/ AND $timeFilter GROUP BY time($interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "read_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "bnpte11cbswj005" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "NETWORK BANDWIDTH",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bytes Received",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 127 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT derivative(max(\"bytes_recv\"),1s) FROM \"net\" WHERE \"host\" =~ /$hostsRegEx/ AND $timeFilter GROUP BY time($interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Bytes Sent",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 127 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT derivative(max(\"bytes_sent\"),1s) FROM \"net\" WHERE \"host\" =~ /$hostsRegEx/ AND $timeFilter GROUP BY time($interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Tcp Connections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 134 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host.established",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"tcp_established\") FROM \"netstat\" WHERE \"host\" =~ /$hostsRegEx/ AND $timeFilter GROUP BY time($__interval), host fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host.close_wait",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"tcp_close_wait\") FROM \"netstat\" WHERE \"host\" =~ /$hostsRegEx/ AND $timeFilter GROUP BY time($__interval), host fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host.time_wait",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"tcp_time_wait\") FROM \"netstat\" WHERE \"host\" =~ /$hostsRegEx/ AND $timeFilter GROUP BY time($__interval), host fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "SYSTEM MEMORY",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "% Memory Util",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 135 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"used_percent\") FROM \"mem\" WHERE \"host\" =~ /$hostsRegEx/ AND $timeFilter GROUP BY time($interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "% Swap Util",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 135 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"used_percent\") FROM \"swap\" WHERE \"host\" =~ /$hostsRegEx/ AND $timeFilter GROUP BY time($interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Pages Swapped in/out",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 135 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host.in",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"in\") FROM \"swap\" WHERE \"host\" =~ /$hostsRegEx/ AND $timeFilter GROUP BY time($interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host.out",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"out\") FROM \"swap\" WHERE \"host\" =~ /$hostsRegEx/ AND $timeFilter GROUP BY time($interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "KERNEL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processes Forked",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 136 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT derivative(max(\"processes_forked\"),1s) FROM \"kernel\" WHERE \"host\" =~ /$hostsRegEx/ AND $timeFilter GROUP BY time($interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "target": "SELECT max(\"context_switches\") FROM \"kernel\" WHERE \"host\" =~ /$hostsRegEx/ AND $timeFilter GROUP BY time($interval), \"host\" fill(null)"
      }
     ]
    },
    {
     "title": "Context Switches",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 136 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT derivative(max(\"context_switches\"),1s) FROM \"kernel\" WHERE \"host\" =~ /$hostsRegEx/ AND $timeFilter GROUP BY time($interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "target": "SELECT max(\"context_switches\") FROM \"kernel\" WHERE \"host\" =~ /$hostsRegEx/ AND $timeFilter GROUP BY time($interval), \"host\" fill(null)"
      }
     ]
    }
   ]
  },
  {
   "title": "PROCESSES",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Running",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 137 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"running\") FROM \"processes\" WHERE \"host\" =~ /$hostsRegEx/ AND $timeFilter GROUP BY time($interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Blocked",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 137 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"blocked\") FROM \"processes\" WHERE \"host\" =~ /$hostsRegEx/ AND $timeFilter GROUP BY time($interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Total",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 144 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"total\") FROM \"processes\" WHERE \"host\" =~ /$hostsRegEx/ AND $timeFilter GROUP BY time($interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Total Threads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 144 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"total_threads\") FROM \"processes\" WHERE \"host\" =~ /$hostsRegEx/ AND $timeFilter GROUP BY time($interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}